apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hola-deployment
  name: hola-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hola-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hola-deployment
    spec:
      containers:
      - image: mavargasucreativa/python-service:2.0.0
        name: python-service
        resources: {}
status: {}
